### ISSUE TITLE
create a new folder yourself if you can't find it

### ISSUE THREAD

**Issue by Jerry-Lau** [ArtSabintsev/Solarized-Dark-for-Xcode#2]
RT.

**Comment by ArtSabintsev** [comment]
Not sure I understand.

**Comment by dw-io** [comment]
He is instructing people to create the ~/Library/Developer/Xcode/UserData/FontAndColorThemes directory, if it doesn't exist.  I think if you add that to the instructions, you can just close this issue.

**Comment by ArtSabintsev** [comment]
How did you get that from `RT`?

**Comment by ArtSabintsev** [comment]
OH - got it. The title and RT = Read Title.
