### ISSUE TITLE
not showing up for me in xcode7

### ISSUE THREAD

**Issue by dw-io** [ArtSabintsev/Solarized-Dark-for-Xcode#3]
Are these instructions valid for xcode7?  I can't get this theme (or any for that matter) to work in xcode7.

**Comment by dw-io** [comment]
Copying to:  /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/Resources/FontAndColorThemes/

Works, so I know the theme is good for this version, but this location is no good since it gets replaced with every Xcode update.  Anyone know where to put themes for 7?

**Comment by ArtSabintsev** [comment]
Install the theme via www.Alcatraz.io - will handle all of that for you.

**Comment by dw-io** [comment]
Did the trick.  I appreciate the help.
